### ISSUE TITLE
Scope for Spring25 release (in preparation)

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/SimSwap#161]
**Problem description**
This issue should describe the scope for the next versions of the APIs within the SimSwap, targeting the Spring25 meta-release.

**Expected action**
### Target versions (tbd)
sim-swap 1.1 (_or 2.0 if new item with breaking change_)
sim-swap-subscriptions 0.2

### Issues with fixes for Spring25 scope

**sim-swap:**
- [x] Add MonitoredPeriod into the API Response if a Telco cannot show the date / data for for Privacy Reasons  #124 
- [x]  Update test wording to avoid confusion with "activation" terminology #170 
- [x] Fix test definition @check_sim_swap_7_no_sim_swap_with_max_age #168 
- [ ] Change error structure as defined in  https://github.com/camaraproject/Commonalities/pull/316 
- [ ] Enhancements and Alignments in Errors https://github.com/camaraproject/Commonalities/pull/329 & https://github.com/camaraproject/Commonalities/pull/324 
- [ ] Remove 500, 503 & 504 errors from the yaml as stated here: https://github.com/camaraproject/Commonalities/issues/321#issuecomment-2429158445  - this topic is still open [here](https://github.com/camaraproject/Commonalities/issues/355) and I suggest to wait discussion outcome before to proceed. 

**sim-swap-subscriptions:**
- [x] Add TerminationReason SUBSCRIPTION_DELETED #177 
- [x] remove allof in sinkcredential #175 

#160 in particular:
- [ ] Error alignments for Event Notifications Artifact - https://github.com/camaraproject/Commonalities/pull/351
- [ ] Align subscription model as defined in https://github.com/camaraproject/Commonalities/pull/313 

**Test definitions:**
- [ ] Align API-Testing-Guidelines with new Enhancements and Alignments in Errors [here](https://github.com/camaraproject/Commonalities/pull/343)

**Additional context**
